# 사용자 정의 속성
profile:
  value: 'test'

spring:
  datasource:
#    url: jdbc:mysql://ssg-java3.iptime.org:3306/auctiondb
#    username: readyauction
#    password: readyauction
    url: jdbc:mysql://localhost:3306/auctiondb
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver